### ISSUE TITLE
Possible to access `kirby.collections`?

### ISSUE THREAD

**Issue by Jorckx** [johannschopplich/kirby-nuxt-starterkit#4]
Hi there :) What a good framework you've build! Everything works like charm for me. It's also very flexible to make it my own. However, I wondered if it's possible to acces a kirby collections? it seems like I can only query the pages and the site.

**Comment by johannschopplich** [comment]
Hi there!

Sure, Kirby collections are supported via [KQL](https://github.com/getkirby/kql). You can use all the KQL methods in Nuxt KQL:

```ts
const { data } = await useKql(
  {
    query: 'collection("articles/latest")',
    pagination: {
      page: 1,
      limit: 8,
    },
    select: {
      uri: true,
      title: true,
      isListed: true,
    },
  },
  { language: locale.value },
)
```

Use `collection()` instead of `kirby.collection` and it will work.

P. S.: This is just the starter kit. If you have further questions, please raise it over at the [Nuxt KQL module repo](https://github.com/johannschopplich/nuxt-kql). Thanks!

**Comment by Jorckx** [comment]
Oh, it was as simple as that. wonderful! I'll take note. Thanks for the quick response. 
And oops, wrong repository indeed :)
